# TRY/CATCH

Es algo muy sabido que Javascript en la espicificacion ES3, especificaba la declaracion de la variable
en el catch clause, de un try/catch para ser blocked scoped, al block the catch.
Por instancia:
```
try {
    undefined(); //illegal operation for force an aception.
}
catch(err) {
    console.log(err); // works
}

console.log(err); // RefferError: `err` not found
```


Como usted puede ver, err solo existe en clause de catch, y envia un error cuando usted trata
de referenciarla en otro lado.

Mientras este comportamiento ha sido especificado y cierto en practicamente en todos los standards de los entornos
de Javascript (exepto por el viejo IE). muchas maquinas parecen todavia si usted tiene uno o mas catch clousures
en el mismo scope que cada uno declare su variable de error con el mismo nombre identificador. Esto no es
una redefinicion, desde que las variables son seguras al block-scope, pero las maquinas parecen ver, molestamente,
se quejan de los nombres de las variables.

Para evitar estos warnings unnecesarios, algunos devs nombran sos catch con variables err1, err2, etc. Otros devs
simplemente apagan la maquina para encontrar nombre de variables iguales.

La naturaleza del block-scoping del catch puede ser vista util desde un punto de vista academico, pero el en apendix
B para mas informacion en que cuan util puede ser.



